### PR TITLE
Update _vimrc

### PR DESCRIPTION
**Pull request by alanyee**
Disable modelines as a security caution

### CODE REVIEW

**Comment by ashishb** [comment]
Hi @alanyee 

Thanks for your contribution. What's this change about? Any links?

**Comment by alanyee** [comment]
https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md spurred me to make explicit changes to my own and other dotfiles. https://security.stackexchange.com/questions/36001/vim-modeline-vulnerabilities lists past vulnerabilities involving the option.

**Comment by ashishb** [comment]
Thanks a lot.

**Comment by ashishb** [comment]
Can you add https://security.stackexchange.com/questions/36001/vim-modeline-vulnerabilities to the comments in _vimrc after `Disable modelines as a security caution`? It would be good to know this before re-enabling this again in the future.

**Pull request merged**
